/**
 * backend/src/client.ts
 *
 * Singleton Anchor Program client.
 *
 * The IDL is imported from the compiled output of `anchor build`.
 * Run `anchor build` in the `onchain-academy/` directory first.
 *
 * The provider uses a NodeWallet wrapping the backend_signer keypair.
 * This is the authority that signs complete_lesson, finalize_course,
 * issue_credential, and upgrade_credential transactions.
 */

import { AnchorProvider, Program, Wallet } from '@coral-xyz/anchor'
import { Connection } from '@solana/web3.js'
import { config } from './config'
import { getBackendSigner } from './keypair'

// Import the IDL from the compiled Anchor output.
// Run: `anchor build` in onchain-academy/ to generate this file.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require('../../../onchain-academy/target/idl/onchain_academy.json')

// Import types (generated by anchor build — used for type safety)
export type OnchainAcademy = typeof IDL

let _connection: Connection | null = null
let _program: Program<OnchainAcademy> | null = null

export function getConnection(): Connection {
    if (!_connection) {
        _connection = new Connection(config.solanaRpcUrl, 'confirmed')
    }
    return _connection
}

export function getProgram(): Program<OnchainAcademy> {
    if (!_program) {
        const connection = getConnection()
        const signer = getBackendSigner()
        const wallet = new Wallet(signer)
        const provider = new AnchorProvider(connection, wallet, {
            commitment: 'confirmed',
            skipPreflight: false,
        })
        _program = new Program<OnchainAcademy>(IDL, provider)
    }
    return _program
}
